// <auto-generated />
using System;
using FavoritesSurvey.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FavoritesSurvey.DAL.Migrations
{
    [DbContext(typeof(FavoritesSurveyContext))]
    [Migration("20210202175705_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FavoritesSurvey.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Earth",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Jupiter",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Venus",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Mercury",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Mars",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Saturn",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Neptune",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Uranus",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Cats",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Dogs",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Birds",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Fish",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Rabbits",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Guinea Pigs",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Europe",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "South America",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Africa",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Asia",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "North America",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Oceania",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Antarctica",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "FPS",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "MMO",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "MOBA",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "RTS",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Turn-based Strategy",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Roguelikes",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Open World",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Sports",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Simulation",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Rock",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Pop",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Hip Hop",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "RnB",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Electronic",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Reggae",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Microsoft",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Apple",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Google",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Amazon",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "IBM",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Intel",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "Oracle",
                            QuestionId = 6
                        });
                });

            modelBuilder.Entity("FavoritesSurvey.Models.ComputedResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ComputedResponses");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite planet in the solar system?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite type of pet?"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite continent?"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite game genre?"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite music genre?"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            DateCreated = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            DateModified = new DateTime(2021, 2, 3, 1, 57, 4, 128, DateTimeKind.Local).AddTicks(4833),
                            IsActive = true,
                            ModifiedBy = 0,
                            Name = "What's your favorite big tech company?"
                        });
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Answer", b =>
                {
                    b.HasOne("FavoritesSurvey.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.ComputedResponse", b =>
                {
                    b.HasOne("FavoritesSurvey.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FavoritesSurvey.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Response", b =>
                {
                    b.HasOne("FavoritesSurvey.Models.Answer", "Answer")
                        .WithMany("Responses")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FavoritesSurvey.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FavoritesSurvey.Models.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Answer", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FavoritesSurvey.Models.Survey", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
